apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-k8s.fullname" . }}
  labels:
    {{- include "go-k8s.labels" . | nindent 4 }}
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: go-k8s.ekstest.link
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "go-k8s.selectorLabels" . | nindent 4 }}
